### ISSUE TITLE
Bot usage statistic 

### ISSUE THREAD

**Issue by Thunder33345** [Botcoins/issue-tracker#10]
Tracking all command usages:

- [x] Short term memory(cleared at restart)

- [x] Long term memory(keep after restart)

Tracking requested currencies:

- [x] Total time a coin's data is requested

- [x] Top requested coins

- [x] Times graph requested

- [x] Times price requested

**Comment by thinkier** [comment]
Short-term and long-term memory are implemented by timestamping every single statistic entry. (All memory is persistent)

**Comment by thinkier** [comment]
Feature finished and deployed.
