### ISSUE TITLE
Add "days" to $cg and $cgd

### ISSUE THREAD

**Issue by pyzeesh** [Botcoins/issue-tracker#28]
At the moment, the graphing commands take the format:

$cgd btc => Defaults to 1-7 day graph however much data is available
$cgd eth btc => Defaults to a 7-day graph against ONLY, throws "Insufficient Data" error if data is less than 7 days

Consider adding support for the following formats:
$cgd btc 10 => Render 10 day BTC USD graph
$cgd eth btc 30 => Render 30 day ETH BTC graph

**Comment by thinkier** [comment]
Main issue #6, right now I am on #18 and I will get to it soon. :)
