### ISSUE TITLE
Add HTH (Help The Homeless Coin)

### ISSUE THREAD

**Issue by sinnx3** [Botcoins/issue-tracker#37]
$cp HTH doesn't bring up results
https://wallet.crypto-bridge.org/market/BRIDGE.HTH_BRIDGE.BTC
http://hthcoin.world/

**Comment by thinkier** [comment]
Hello, unfortunately there is nothing I can do if CoinMarketCap doesn’t list it, as the bot depends on it. Please contact them for listing.

**Comment by thinkier** [comment]
![it's in there now](https://cdn.discordapp.com/attachments/428833491468156929/512593047511498753/unknown.png)
