### ISSUE TITLE
Threading and async system should be moved into a thread pool

### ISSUE THREAD

**Issue by ConcurrentMarxistGC** [Botcoins/issue-tracker#5]

**Comment by thinkier** [comment]
- [x] The request system was moved into a scheduled thread pool due to a restructure to optimize speed.
- [x] Move nick update / playing field updates into a scheduled thread pool

**Comment by thinkier** [comment]
`Playing [...]` field can't be optimized further, a single thread with sleep delay cycling through all the providers will have to do.
