### ISSUE TITLE
$cgraph enhancements

### ISSUE THREAD

**Issue by ConcurrentMarxistGC** [Botcoins/issue-tracker#6]
- [x] Modify the colours to be more beautiful
- [x] Fix the fucked up drops
- [x] Start caching the data from live fetches
- [x] Proactively use cached data and stop hitting CMC for historical data
- [x] Ability to choose dark theme 😈 
- [x] Ability to choose any crypto pair (though defaults to ???usd)
- [x] Ability to choose timeframe (days or whatever)
- [x] ~~Ability to choose any fiat pair~~ not practical
- [x] Indicators (in file name for cache discrimination)
- [x] Bollinger Bands
- [x] EMA
- [x] DEMA
- [x] RSI
- [x] Volume

**Comment by thinkier** [comment]
- [x] Sticks look a bit broken right now, fix candle::stick l->c

**Comment by thinkier** [comment]
For volume please reference #35, otherwise it's ready on branch `volume`
